### ISSUE TITLE
Debugging is in-disablable

### ISSUE THREAD

**Issue by thebitstick** [mharrys/flask-blog#2]
Having "Debug = False" in the config.py doesn't do a thing.

**Comment by mharrys** [comment]
Thanks. It was a while since I used this repo but I believe some package not listed in requirement.txt was updated and broke it for flask-script. I have updated flask-script and from a clean python environment set explicit version on all packages used.

Now setting DEBUG=True will enable the debugger and DEBUG=False (or None) will run without a debugger.

[More info on DEBUG in config file](http://flask.pocoo.org/docs/0.10/config/)
[More info on DEBUG in flask-script](https://flask-script.readthedocs.org/en/latest/)

**Comment by thebitstick** [comment]
Disabling Debugging gives this error when logged in:

``` Python
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1410, in handle_exception
    return handler(e)
  File "/home/jorge/flask-blog/app/views.py", line 29, in internal_server_error
    return render_template('error/500.html'), 500
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jorge/flask-blog/app/templates/error/500.html", line 1, in top-level template code
    {% extends "error/layout.html" %}
  File "/home/jorge/flask-blog/app/templates/error/layout.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jorge/flask-blog/app/templates/base.html", line 13, in top-level template code
    {% block body %}{% endblock %}
  File "/home/jorge/flask-blog/app/templates/error/layout.html", line 17, in block "body"
    <a href="{{ url_for('blog') }}">Back to blog</a>{% if current_user.is_authenticated() %} or <a href="{{ url_for('admin.overview') }}">Back to admin</a>{% endif %}
UndefinedError: 'None' has no attribute 'is_authenticated'
```

And when unlogged in, it displays Bootstrap error pages

**Comment by mharrys** [comment]
I set it such that when debug is disabled it will connect to a running database as can be observed in config.py. This was when I had it deployed a while back.

``` python
import os

DEBUG = True
SECRET_KEY = 'dev'

if DEBUG:
    root = os.path.abspath(os.path.dirname(__file__))
    SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(root, 'sqlite3.db')
else:
    db = 'database'
    username = 'username'
    password = 'password'
    uri = 'postgres://%s:%s@localhost:5432/%s' % (username, password, db)
    SQLALCHEMY_DATABASE_URI = uri
```

If you don't want this and just want to use sqlite in both cases you could update config.py to the following

``` python
import os

DEBUG = True
SECRET_KEY = 'dev'

root = os.path.abspath(os.path.dirname(__file__))
SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(root, 'sqlite3.db')
```

DEBUG is not just for this case but is read by Flask too which will enable/disable the debugger on error.

**Comment by thebitstick** [comment]
Thank you so much
I didn't think to check that part
